-- 清结算平台 P0 DDL - V004 正式规范对齐版
-- Database: MySQL 8.x
-- 规范约定：
-- 1. 金额字段统一 BIGINT，单位分，人民币。
-- 2. 当前阶段不设计 currency / cur / currency_code 字段。
-- 3. 当前阶段不设计 tenant_id 字段。
-- 4. 主键统一 BIGINT UNSIGNED。
-- 5. 时间字段统一 DATETIME(3)。
-- 6. 逻辑删除字段 deleted：0=未删除，1=已删除。
-- 7. request_hash 不参与唯一索引，只用于同一幂等键下的请求一致性校验。

CREATE TABLE IF NOT EXISTS ccs_source_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  event_no VARCHAR(64) NOT NULL COMMENT '清结算平台事件号',
  caller_system VARCHAR(64) NOT NULL COMMENT '技术调用方系统，如 LOCAL_LIFE_ORDER',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务归属域，如 LOCAL_LIFE',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务单号，由 biz_domain 解释',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景，如 LOCAL_LIFE_NORMAL_GOODS',
  event_type VARCHAR(64) NOT NULL COMMENT '事件类型：WRITE_OFF_COMPLETED/REFUND_SUCCESS/WRITE_OFF_CANCELED',
  source_event_no VARCHAR(128) NOT NULL COMMENT '来源事件唯一号',
  source_order_no VARCHAR(128) DEFAULT NULL COMMENT '来源订单号',
  source_write_off_no VARCHAR(128) DEFAULT NULL COMMENT '来源核销单号',
  source_refund_no VARCHAR(128) DEFAULT NULL COMMENT '来源退款单号',
  event_occur_time DATETIME(3) NOT NULL COMMENT '业务事件发生时间',
  idempotent_key VARCHAR(256) NOT NULL COMMENT '事件接入幂等键',
  request_hash VARCHAR(128) NOT NULL COMMENT '事件核心参数指纹',
  payload_json JSON NOT NULL COMMENT '原始事件载荷',
  process_status VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT 'INIT/PROCESSING/SUCCESS/FAILED/IGNORED/WAITING',
  process_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '处理次数',
  next_retry_time DATETIME(3) DEFAULT NULL COMMENT '下次重试时间',
  last_error_code VARCHAR(64) DEFAULT NULL COMMENT '最后错误码',
  last_error_message VARCHAR(512) DEFAULT NULL COMMENT '最后错误信息',
  version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_source_event_no (event_no),
  UNIQUE KEY uk_ccs_source_event_idem (idempotent_key),
  UNIQUE KEY uk_ccs_source_event_source (caller_system, biz_domain, event_type, source_event_no, deleted),
  KEY idx_ccs_source_event_biz (biz_domain, biz_no),
  KEY idx_ccs_source_event_status (process_status, next_retry_time),
  KEY idx_ccs_source_event_order (source_order_no),
  KEY idx_ccs_source_event_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='清结算来源事件表';

CREATE TABLE IF NOT EXISTS ccs_clearing_result (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  clearing_no VARCHAR(64) NOT NULL COMMENT '清分结果号',
  event_no VARCHAR(64) NOT NULL COMMENT '来源事件号',
  caller_system VARCHAR(64) NOT NULL COMMENT '技术调用方系统',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务归属域',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务单号',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  order_type VARCHAR(64) NOT NULL DEFAULT 'NORMAL_GOODS' COMMENT '订单类型',
  source_order_no VARCHAR(128) NOT NULL COMMENT '业务订单号',
  write_off_no VARCHAR(128) DEFAULT NULL COMMENT '核销单号',
  refund_no VARCHAR(128) DEFAULT NULL COMMENT '退款单号',
  merchant_id VARCHAR(64) NOT NULL COMMENT '商户ID',
  merchant_name VARCHAR(128) DEFAULT NULL COMMENT '商户名称快照',
  direction VARCHAR(16) NOT NULL DEFAULT 'POSITIVE' COMMENT 'POSITIVE/NEGATIVE',
  order_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '订单金额，单位分，人民币',
  paid_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '用户实付金额，单位分，人民币',
  refund_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '本次退款金额，单位分，人民币',
  merchant_receivable_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '商户应结金额，单位分，人民币',
  platform_receivable_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '平台应收金额，单位分，人民币',
  platform_discount_cost_cent BIGINT NOT NULL DEFAULT 0 COMMENT '平台优惠成本，单位分，人民币',
  merchant_discount_cost_cent BIGINT NOT NULL DEFAULT 0 COMMENT '商户优惠成本，单位分，人民币',
  member_discount_cost_cent BIGINT NOT NULL DEFAULT 0 COMMENT '会员折扣成本，单位分，人民币',
  points_cost_cent BIGINT NOT NULL DEFAULT 0 COMMENT '金豆/积分成本，单位分，人民币',
  rule_snapshot_no VARCHAR(64) DEFAULT NULL COMMENT '规则快照号',
  clearing_status VARCHAR(32) NOT NULL DEFAULT 'GENERATED' COMMENT 'GENERATED/CANCELED/ADJUSTED',
  idempotent_key VARCHAR(256) NOT NULL COMMENT '清分幂等键',
  request_hash VARCHAR(128) NOT NULL COMMENT '清分核心参数指纹',
  version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_clearing_no (clearing_no),
  UNIQUE KEY uk_ccs_clearing_event (event_no, deleted),
  UNIQUE KEY uk_ccs_clearing_idem (idempotent_key),
  KEY idx_ccs_clearing_biz (caller_system, biz_domain, biz_no),
  KEY idx_ccs_clearing_order (business_scene, source_order_no),
  KEY idx_ccs_clearing_merchant (merchant_id, create_time),
  KEY idx_ccs_clearing_status (clearing_status, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='清分结果主表';

CREATE TABLE IF NOT EXISTS ccs_clearing_result_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  clearing_item_no VARCHAR(64) NOT NULL COMMENT '清分明细号',
  clearing_no VARCHAR(64) NOT NULL COMMENT '清分结果号',
  source_order_no VARCHAR(128) NOT NULL COMMENT '业务订单号',
  participant_type VARCHAR(32) NOT NULL COMMENT '参与方类型：MERCHANT/PLATFORM',
  participant_id VARCHAR(64) NOT NULL COMMENT '参与方ID',
  participant_name VARCHAR(128) DEFAULT NULL COMMENT '参与方名称快照',
  amount_type VARCHAR(64) NOT NULL COMMENT '金额类型：MERCHANT_RECEIVABLE/PLATFORM_RECEIVABLE/DISCOUNT_COST/REFUND_ADJUSTMENT',
  direction VARCHAR(16) NOT NULL COMMENT '记账方向：CREDIT/DEBIT',
  amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '金额，单位分，人民币，方向由 direction 表达',
  settlement_subject_type VARCHAR(32) NOT NULL COMMENT '结算主体类型：MERCHANT/PLATFORM',
  settlement_subject_id VARCHAR(64) NOT NULL COMMENT '结算主体ID',
  formula_code VARCHAR(64) DEFAULT NULL COMMENT '公式编码',
  formula_text VARCHAR(512) DEFAULT NULL COMMENT '公式快照',
  version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_clearing_item_no (clearing_item_no),
  UNIQUE KEY uk_ccs_clearing_item_biz (clearing_no, participant_type, participant_id, amount_type, direction, deleted),
  KEY idx_ccs_clearing_item_clearing (clearing_no),
  KEY idx_ccs_clearing_item_subject (settlement_subject_type, settlement_subject_id),
  KEY idx_ccs_clearing_item_order (source_order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='清分结果明细表';

CREATE TABLE IF NOT EXISTS ccs_pending_settlement_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  pending_no VARCHAR(64) NOT NULL COMMENT '待结算项号',
  clearing_item_no VARCHAR(64) NOT NULL COMMENT '来源清分明细号',
  clearing_no VARCHAR(64) NOT NULL COMMENT '来源清分结果号',
  caller_system VARCHAR(64) NOT NULL COMMENT '技术调用方系统',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务归属域',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务单号',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  source_order_no VARCHAR(128) NOT NULL COMMENT '业务订单号',
  write_off_no VARCHAR(128) DEFAULT NULL COMMENT '核销单号',
  merchant_id VARCHAR(64) NOT NULL COMMENT '商户ID',
  merchant_name VARCHAR(128) DEFAULT NULL COMMENT '商户名称快照',
  settlement_subject_type VARCHAR(32) NOT NULL DEFAULT 'MERCHANT' COMMENT '结算主体类型',
  settlement_subject_id VARCHAR(64) NOT NULL COMMENT '结算主体ID',
  original_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '原始待结算金额，单位分，人民币',
  adjusted_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '退款/调整金额，单位分，人民币，负数表示扣减',
  settlement_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '当前待结算金额，单位分，人民币',
  write_off_time DATETIME(3) NOT NULL COMMENT '核销/履约完成时间',
  eligible_time DATETIME(3) NOT NULL COMMENT '可结算时间',
  lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'IN_TRANSIT' COMMENT 'IN_TRANSIT/ELIGIBLE/LOCKED/ACCOUNTING_PROCESSING/ACCOUNTING_FAILED/ACCOUNTED/CANCELED',
  locked_batch_no VARCHAR(64) DEFAULT NULL COMMENT '锁定批次号',
  locked_bill_no VARCHAR(64) DEFAULT NULL COMMENT '锁定结算单号',
  locked_time DATETIME(3) DEFAULT NULL COMMENT '锁定时间',
  accounted_time DATETIME(3) DEFAULT NULL COMMENT '入账成功时间',
  refund_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT 'NONE/PARTIAL_REFUNDED/FULL_REFUNDED/AFTER_ACCOUNTING_REFUNDED',
  version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_pending_no (pending_no),
  UNIQUE KEY uk_ccs_pending_clearing_item (clearing_item_no, deleted),
  KEY idx_ccs_pending_payable (merchant_id, lifecycle_status, eligible_time),
  KEY idx_ccs_pending_biz (caller_system, biz_domain, biz_no),
  KEY idx_ccs_pending_order (source_order_no),
  KEY idx_ccs_pending_bill (locked_bill_no),
  KEY idx_ccs_pending_status_time (lifecycle_status, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='待结算项表';

CREATE TABLE IF NOT EXISTS ccs_settlement_batch (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  batch_no VARCHAR(64) NOT NULL COMMENT '结算批次号',
  caller_system VARCHAR(64) NOT NULL COMMENT '技术调用方系统',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务归属域',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务单号',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  batch_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT 'MANUAL/AUTO',
  settlement_subject_type VARCHAR(32) NOT NULL DEFAULT 'MERCHANT' COMMENT '结算主体类型',
  settlement_subject_id VARCHAR(64) NOT NULL COMMENT '结算主体ID',
  merchant_id VARCHAR(64) NOT NULL COMMENT '商户ID',
  item_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '明细数量',
  total_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '批次总金额，单位分，人民币',
  batch_status VARCHAR(32) NOT NULL DEFAULT 'CREATED' COMMENT 'CREATED/PROCESSING/FINISHED/FAILED/CANCELED',
  operator_id VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
  operator_name VARCHAR(64) DEFAULT NULL COMMENT '操作人名称',
  request_hash VARCHAR(128) NOT NULL COMMENT '批次请求核心参数指纹',
  version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_batch_no (batch_no),
  KEY idx_ccs_batch_subject (settlement_subject_type, settlement_subject_id, create_time),
  KEY idx_ccs_batch_status (batch_status, create_time),
  KEY idx_ccs_batch_biz (caller_system, biz_domain, biz_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='结算批次表';

CREATE TABLE IF NOT EXISTS ccs_settlement_bill (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  bill_no VARCHAR(64) NOT NULL COMMENT '结算单号',
  batch_no VARCHAR(64) NOT NULL COMMENT '结算批次号',
  caller_system VARCHAR(64) NOT NULL COMMENT '技术调用方系统',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务归属域',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务单号',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  settlement_subject_type VARCHAR(32) NOT NULL DEFAULT 'MERCHANT' COMMENT '结算主体类型',
  settlement_subject_id VARCHAR(64) NOT NULL COMMENT '结算主体ID',
  merchant_id VARCHAR(64) NOT NULL COMMENT '商户ID',
  merchant_name VARCHAR(128) DEFAULT NULL COMMENT '商户名称快照',
  bill_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '结算单金额，单位分，人民币',
  item_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '明细数量',
  settlement_start_time DATETIME(3) DEFAULT NULL COMMENT '结算范围开始',
  settlement_end_time DATETIME(3) DEFAULT NULL COMMENT '结算范围结束',
  bill_status VARCHAR(32) NOT NULL DEFAULT 'CREATED' COMMENT 'CREATED/CONFIRMED/ACCOUNTING_PROCESSING/ACCOUNTED/ACCOUNTING_FAILED/UNKNOWN/CANCELED',
  accounting_status VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT 'INIT/PROCESSING/SUCCESS/FAILED/UNKNOWN',
  idempotent_key VARCHAR(256) NOT NULL COMMENT '结算确认幂等键',
  request_hash VARCHAR(128) NOT NULL COMMENT '结算确认请求核心参数指纹',
  accounting_idempotent_key VARCHAR(256) DEFAULT NULL COMMENT '账务入账幂等键',
  accounting_request_no VARCHAR(64) DEFAULT NULL COMMENT '账务请求号',
  fund_account_flow_no VARCHAR(64) DEFAULT NULL COMMENT '账户流水号',
  voucher_urls VARCHAR(2048) DEFAULT NULL COMMENT '结算凭证URL，逗号分隔或JSON字符串',
  fail_code VARCHAR(64) DEFAULT NULL COMMENT '失败错误码',
  fail_reason VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
  retry_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '重试次数',
  operator_id VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
  operator_name VARCHAR(64) DEFAULT NULL COMMENT '操作人名称',
  confirmed_time DATETIME(3) DEFAULT NULL COMMENT '确认时间',
  accounting_success_time DATETIME(3) DEFAULT NULL COMMENT '账务成功时间',
  version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_bill_no (bill_no),
  UNIQUE KEY uk_ccs_bill_idem (idempotent_key),
  UNIQUE KEY uk_ccs_bill_accounting_idem (accounting_idempotent_key),
  UNIQUE KEY uk_ccs_bill_biz (caller_system, biz_domain, biz_no, business_scene, deleted),
  KEY idx_ccs_bill_merchant (merchant_id, create_time),
  KEY idx_ccs_bill_status (bill_status, create_time),
  KEY idx_ccs_bill_batch (batch_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='结算单主表';

CREATE TABLE IF NOT EXISTS ccs_settlement_bill_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  bill_item_no VARCHAR(64) NOT NULL COMMENT '结算单明细号',
  bill_no VARCHAR(64) NOT NULL COMMENT '结算单号',
  batch_no VARCHAR(64) NOT NULL COMMENT '结算批次号',
  pending_no VARCHAR(64) NOT NULL COMMENT '待结算项号',
  clearing_item_no VARCHAR(64) NOT NULL COMMENT '清分明细号',
  source_order_no VARCHAR(128) NOT NULL COMMENT '业务订单号',
  write_off_no VARCHAR(128) DEFAULT NULL COMMENT '核销单号',
  merchant_id VARCHAR(64) NOT NULL COMMENT '商户ID',
  settlement_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '结算金额，单位分，人民币',
  item_status VARCHAR(32) NOT NULL DEFAULT 'LOCKED' COMMENT 'LOCKED/ACCOUNTING_PROCESSING/ACCOUNTED/ACCOUNTING_FAILED/CANCELED',
  settlement_success_key VARCHAR(128) DEFAULT NULL COMMENT '入账成功防重键，成功时写 pending_no，未成功为NULL',
  version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_bill_item_no (bill_item_no),
  UNIQUE KEY uk_ccs_bill_item_pending (pending_no, deleted),
  UNIQUE KEY uk_ccs_bill_item_success (settlement_success_key),
  KEY idx_ccs_bill_item_bill (bill_no),
  KEY idx_ccs_bill_item_pending (pending_no),
  KEY idx_ccs_bill_item_order (source_order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='结算单明细表';

CREATE TABLE IF NOT EXISTS ccs_accounting_posting_order (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  posting_no VARCHAR(64) NOT NULL COMMENT '入账单号',
  bill_no VARCHAR(64) NOT NULL COMMENT '结算单号',
  caller_system VARCHAR(64) NOT NULL COMMENT '技术调用方系统',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务归属域',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务单号',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  merchant_id VARCHAR(64) NOT NULL COMMENT '商户ID',
  posting_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '入账金额，单位分，人民币',
  accounting_interface VARCHAR(64) NOT NULL DEFAULT 'recordProductSettlement' COMMENT '调用账务接口',
  accounting_scene VARCHAR(64) NOT NULL DEFAULT 'PRODUCT_SETTLEMENT' COMMENT '账务场景',
  idempotent_key VARCHAR(256) NOT NULL COMMENT '账务入账幂等键',
  request_hash VARCHAR(128) NOT NULL COMMENT '账务入账核心参数指纹',
  posting_status VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT 'INIT/REQUESTING/SUCCESS/FAILED/UNKNOWN',
  request_payload JSON DEFAULT NULL COMMENT '账务请求快照',
  response_payload JSON DEFAULT NULL COMMENT '账务响应快照',
  accounting_request_no VARCHAR(64) DEFAULT NULL COMMENT '账务请求号',
  fund_account_flow_no VARCHAR(64) DEFAULT NULL COMMENT '账户流水号',
  fail_code VARCHAR(64) DEFAULT NULL COMMENT '失败错误码',
  fail_reason VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
  request_time DATETIME(3) DEFAULT NULL COMMENT '请求时间',
  success_time DATETIME(3) DEFAULT NULL COMMENT '成功时间',
  retry_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '重试次数',
  next_retry_time DATETIME(3) DEFAULT NULL COMMENT '下次重试时间',
  version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_posting_no (posting_no),
  UNIQUE KEY uk_ccs_posting_bill (bill_no, deleted),
  UNIQUE KEY uk_ccs_posting_idem (idempotent_key),
  UNIQUE KEY uk_ccs_posting_biz (caller_system, biz_domain, biz_no, accounting_scene, deleted),
  KEY idx_ccs_posting_status (posting_status, next_retry_time),
  KEY idx_ccs_posting_merchant (merchant_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='账务入账编排单';

CREATE TABLE IF NOT EXISTS ccs_settlement_operation_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  operation_no VARCHAR(64) NOT NULL COMMENT '操作日志号',
  target_type VARCHAR(64) NOT NULL COMMENT 'PENDING_ITEM/SETTLEMENT_BILL/POSTING_ORDER',
  target_no VARCHAR(64) NOT NULL COMMENT '目标单号',
  operation_type VARCHAR(64) NOT NULL COMMENT 'CREATE/CONFIRM/CANCEL/POSTING/RETRY/REPAIR/STATE_CHANGE',
  before_status VARCHAR(32) DEFAULT NULL COMMENT '操作前状态',
  after_status VARCHAR(32) DEFAULT NULL COMMENT '操作后状态',
  operator_id VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
  operator_name VARCHAR(64) DEFAULT NULL COMMENT '操作人名称',
  trace_id VARCHAR(128) DEFAULT NULL COMMENT '链路追踪ID',
  remark VARCHAR(512) DEFAULT NULL COMMENT '备注',
  ext_json JSON DEFAULT NULL COMMENT '扩展信息',
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除，1已删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_operation_no (operation_no),
  KEY idx_ccs_operation_target (target_type, target_no),
  KEY idx_ccs_operation_type_time (operation_type, create_time),
  KEY idx_ccs_operation_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='清结算操作日志表';
