-- 清结算平台 V005 P0 DDL
-- 规范：金额 BIGINT 分；不设置币种列；不设置租户列；不设置退款列；不设置旧系统映射列。

CREATE TABLE IF NOT EXISTS ccs_source_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  event_no VARCHAR(64) NOT NULL COMMENT '清结算来源事件编号',
  caller_system VARCHAR(64) NOT NULL COMMENT '调用系统',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务域',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务请求号',
  event_type VARCHAR(64) NOT NULL COMMENT '事件类型：FULFILLMENT_CONFIRMED',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  source_order_no VARCHAR(128) NOT NULL COMMENT '来源订单号',
  source_fulfillment_no VARCHAR(128) NOT NULL COMMENT '来源履约/核销号',
  merchant_no VARCHAR(64) NOT NULL COMMENT '商户编号',
  fulfillment_time DATETIME(3) NOT NULL COMMENT '履约/核销完成时间',
  order_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '订单金额，单位分，人民币',
  paid_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '用户实付金额，单位分，人民币',
  merchant_receivable_cent BIGINT NOT NULL DEFAULT 0 COMMENT '商户应结金额，单位分，人民币',
  platform_receivable_cent BIGINT NOT NULL DEFAULT 0 COMMENT '平台应收金额，单位分，人民币',
  discount_cost_cent BIGINT NOT NULL DEFAULT 0 COMMENT '优惠成本金额，单位分，人民币',
  event_payload_json JSON DEFAULT NULL COMMENT '标准事件扩展载荷',
  process_status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED' COMMENT '处理状态：RECEIVED/PROCESSED/FAILED/IGNORED',
  fail_reason VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
  idempotent_key VARCHAR(128) NOT NULL COMMENT '幂等键',
  request_hash VARCHAR(128) NOT NULL COMMENT '请求核心参数指纹',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_source_event_no (event_no),
  UNIQUE KEY uk_ccs_source_event_idem (idempotent_key),
  UNIQUE KEY uk_ccs_source_event_biz (caller_system, biz_domain, biz_no),
  UNIQUE KEY uk_ccs_source_event_source (source_order_no, source_fulfillment_no, event_type),
  KEY idx_ccs_source_event_status (process_status, create_time),
  KEY idx_ccs_source_event_merchant (merchant_no, fulfillment_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='清结算来源事件表';

CREATE TABLE IF NOT EXISTS ccs_clearing_result (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  clearing_no VARCHAR(64) NOT NULL COMMENT '清分结果编号',
  event_no VARCHAR(64) NOT NULL COMMENT '来源事件编号',
  caller_system VARCHAR(64) NOT NULL COMMENT '调用系统',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务域',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务请求号',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  source_order_no VARCHAR(128) NOT NULL COMMENT '来源订单号',
  source_fulfillment_no VARCHAR(128) NOT NULL COMMENT '来源履约/核销号',
  merchant_no VARCHAR(64) NOT NULL COMMENT '商户编号',
  order_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '订单金额，单位分，人民币',
  paid_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '用户实付金额，单位分，人民币',
  merchant_receivable_cent BIGINT NOT NULL DEFAULT 0 COMMENT '商户应结金额，单位分，人民币',
  platform_receivable_cent BIGINT NOT NULL DEFAULT 0 COMMENT '平台应收金额，单位分，人民币',
  discount_cost_cent BIGINT NOT NULL DEFAULT 0 COMMENT '优惠成本金额，单位分，人民币',
  clearing_status VARCHAR(32) NOT NULL DEFAULT 'CLEARED' COMMENT '清分状态：CLEARED/FAILED',
  rule_snapshot_json JSON DEFAULT NULL COMMENT '清分规则快照',
  fail_reason VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
  idempotent_key VARCHAR(128) NOT NULL COMMENT '幂等键',
  request_hash VARCHAR(128) NOT NULL COMMENT '请求核心参数指纹',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_clearing_no (clearing_no),
  UNIQUE KEY uk_ccs_clearing_event (event_no),
  UNIQUE KEY uk_ccs_clearing_idem (idempotent_key),
  KEY idx_ccs_clearing_source (source_order_no, source_fulfillment_no),
  KEY idx_ccs_clearing_merchant (merchant_no, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='清分结果表';

CREATE TABLE IF NOT EXISTS ccs_clearing_result_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  clearing_item_no VARCHAR(64) NOT NULL COMMENT '清分明细编号',
  clearing_no VARCHAR(64) NOT NULL COMMENT '清分结果编号',
  participant_type VARCHAR(32) NOT NULL COMMENT '参与方类型：MERCHANT/PLATFORM',
  participant_no VARCHAR(64) NOT NULL COMMENT '参与方编号',
  amount_type VARCHAR(64) NOT NULL COMMENT '金额类型：MERCHANT_RECEIVABLE/PLATFORM_RECEIVABLE/DISCOUNT_COST',
  amount_direction VARCHAR(16) NOT NULL DEFAULT 'INCREASE' COMMENT '金额方向：INCREASE',
  amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '金额，单位分，人民币',
  settlement_required TINYINT NOT NULL DEFAULT 1 COMMENT '是否需要进入结算头寸',
  item_status VARCHAR(32) NOT NULL DEFAULT 'CLEARED' COMMENT '明细状态：CLEARED/FAILED',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_clearing_item_no (clearing_item_no),
  UNIQUE KEY uk_ccs_clearing_item_participant (clearing_no, participant_type, participant_no, amount_type),
  KEY idx_ccs_clearing_item_clearing (clearing_no),
  KEY idx_ccs_clearing_item_participant (participant_type, participant_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='清分明细表';

CREATE TABLE IF NOT EXISTS ccs_settlement_position (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  position_no VARCHAR(64) NOT NULL COMMENT '结算头寸编号',
  clearing_no VARCHAR(64) NOT NULL COMMENT '清分结果编号',
  clearing_item_no VARCHAR(64) NOT NULL COMMENT '清分明细编号',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  source_order_no VARCHAR(128) NOT NULL COMMENT '来源订单号',
  source_fulfillment_no VARCHAR(128) NOT NULL COMMENT '来源履约/核销号',
  settlement_target_type VARCHAR(32) NOT NULL COMMENT '结算对象类型：MERCHANT',
  settlement_target_no VARCHAR(64) NOT NULL COMMENT '结算对象编号',
  settlement_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '结算金额，单位分，人民币',
  in_transit_time DATETIME(3) NOT NULL COMMENT '进入在途时间',
  eligible_time DATETIME(3) NOT NULL COMMENT '可结算时间',
  lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'IN_TRANSIT' COMMENT '生命周期状态：IN_TRANSIT/ELIGIBLE/LOCKED/ACCOUNTING_PROCESSING/ACCOUNTING_FAILED/UNKNOWN/ACCOUNTED',
  locked_batch_no VARCHAR(64) DEFAULT NULL COMMENT '锁定批次号',
  locked_bill_no VARCHAR(64) DEFAULT NULL COMMENT '锁定结算单号',
  posting_no VARCHAR(64) DEFAULT NULL COMMENT '账务入账单号',
  accounted_time DATETIME(3) DEFAULT NULL COMMENT '入账成功时间',
  fail_reason VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_position_no (position_no),
  UNIQUE KEY uk_ccs_position_clearing_item (clearing_item_no),
  KEY idx_ccs_position_eligible (lifecycle_status, eligible_time),
  KEY idx_ccs_position_target (settlement_target_type, settlement_target_no, lifecycle_status),
  KEY idx_ccs_position_bill (locked_bill_no),
  KEY idx_ccs_position_source (source_order_no, source_fulfillment_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='结算头寸表';

CREATE TABLE IF NOT EXISTS ccs_settlement_batch (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  batch_no VARCHAR(64) NOT NULL COMMENT '结算批次号',
  batch_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '批次类型：MANUAL/AUTO',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  settlement_target_type VARCHAR(32) NOT NULL COMMENT '结算对象类型：MERCHANT',
  settlement_target_no VARCHAR(64) NOT NULL COMMENT '结算对象编号',
  position_count INT NOT NULL DEFAULT 0 COMMENT '头寸数量',
  total_settlement_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '批次结算总金额，单位分，人民币',
  batch_status VARCHAR(32) NOT NULL DEFAULT 'CREATED' COMMENT '批次状态：CREATED/CONFIRMED/ACCOUNTING_PROCESSING/ACCOUNTED/ACCOUNTING_FAILED/UNKNOWN/CANCELED',
  operator_id VARCHAR(64) NOT NULL COMMENT '操作人ID',
  operator_name VARCHAR(128) DEFAULT NULL COMMENT '操作人名称',
  confirm_time DATETIME(3) DEFAULT NULL COMMENT '确认时间',
  idempotent_key VARCHAR(128) NOT NULL COMMENT '幂等键',
  request_hash VARCHAR(128) NOT NULL COMMENT '请求核心参数指纹',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_batch_no (batch_no),
  UNIQUE KEY uk_ccs_batch_idem (idempotent_key),
  KEY idx_ccs_batch_target (settlement_target_type, settlement_target_no, create_time),
  KEY idx_ccs_batch_status (batch_status, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='结算批次表';

CREATE TABLE IF NOT EXISTS ccs_settlement_bill (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  bill_no VARCHAR(64) NOT NULL COMMENT '结算单号',
  batch_no VARCHAR(64) NOT NULL COMMENT '结算批次号',
  caller_system VARCHAR(64) NOT NULL COMMENT '调用系统',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务域',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务请求号',
  business_scene VARCHAR(64) NOT NULL COMMENT '业务场景',
  settlement_target_type VARCHAR(32) NOT NULL COMMENT '结算对象类型：MERCHANT',
  settlement_target_no VARCHAR(64) NOT NULL COMMENT '结算对象编号',
  position_count INT NOT NULL DEFAULT 0 COMMENT '头寸数量',
  bill_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '结算单金额，单位分，人民币',
  posting_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '账务入账金额，单位分，人民币',
  bill_status VARCHAR(32) NOT NULL DEFAULT 'CREATED' COMMENT '结算单状态：CREATED/CONFIRMED/ACCOUNTING_PROCESSING/ACCOUNTED/ACCOUNTING_FAILED/UNKNOWN/CANCELED',
  voucher_url VARCHAR(512) DEFAULT NULL COMMENT '结算凭证地址',
  operator_id VARCHAR(64) NOT NULL COMMENT '操作人ID',
  operator_name VARCHAR(128) DEFAULT NULL COMMENT '操作人名称',
  confirm_time DATETIME(3) DEFAULT NULL COMMENT '确认时间',
  accounting_request_no VARCHAR(64) DEFAULT NULL COMMENT '账务请求号',
  fund_account_flow_no VARCHAR(64) DEFAULT NULL COMMENT '账户流水号',
  accounted_time DATETIME(3) DEFAULT NULL COMMENT '入账成功时间',
  fail_reason VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
  idempotent_key VARCHAR(128) NOT NULL COMMENT '幂等键',
  request_hash VARCHAR(128) NOT NULL COMMENT '请求核心参数指纹',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_bill_no (bill_no),
  UNIQUE KEY uk_ccs_bill_biz (caller_system, biz_domain, biz_no),
  UNIQUE KEY uk_ccs_bill_idem (idempotent_key),
  KEY idx_ccs_bill_batch (batch_no),
  KEY idx_ccs_bill_target (settlement_target_type, settlement_target_no, create_time),
  KEY idx_ccs_bill_status (bill_status, create_time),
  KEY idx_ccs_bill_accounting (accounting_request_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='结算单表';

CREATE TABLE IF NOT EXISTS ccs_settlement_bill_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  bill_item_no VARCHAR(64) NOT NULL COMMENT '结算单明细号',
  bill_no VARCHAR(64) NOT NULL COMMENT '结算单号',
  batch_no VARCHAR(64) NOT NULL COMMENT '结算批次号',
  position_no VARCHAR(64) NOT NULL COMMENT '结算头寸编号',
  clearing_item_no VARCHAR(64) NOT NULL COMMENT '清分明细编号',
  source_order_no VARCHAR(128) NOT NULL COMMENT '来源订单号',
  source_fulfillment_no VARCHAR(128) NOT NULL COMMENT '来源履约/核销号',
  settlement_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '结算金额，单位分，人民币',
  item_status VARCHAR(32) NOT NULL DEFAULT 'LOCKED' COMMENT '明细状态：LOCKED/ACCOUNTING_PROCESSING/ACCOUNTED/ACCOUNTING_FAILED/UNKNOWN',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_bill_item_no (bill_item_no),
  UNIQUE KEY uk_ccs_bill_item_position (position_no),
  KEY idx_ccs_bill_item_bill (bill_no),
  KEY idx_ccs_bill_item_batch (batch_no),
  KEY idx_ccs_bill_item_source (source_order_no, source_fulfillment_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='结算单明细表';

CREATE TABLE IF NOT EXISTS ccs_accounting_posting_order (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  posting_no VARCHAR(64) NOT NULL COMMENT '账务入账单号',
  bill_no VARCHAR(64) NOT NULL COMMENT '结算单号',
  batch_no VARCHAR(64) NOT NULL COMMENT '结算批次号',
  caller_system VARCHAR(64) NOT NULL COMMENT '调用系统',
  biz_domain VARCHAR(64) NOT NULL COMMENT '业务域',
  biz_no VARCHAR(128) NOT NULL COMMENT '业务请求号，通常为结算单号',
  accounting_scene VARCHAR(64) NOT NULL COMMENT '账务场景：MERCHANT_SETTLEMENT_POSTING',
  settlement_target_type VARCHAR(32) NOT NULL COMMENT '结算对象类型：MERCHANT',
  settlement_target_no VARCHAR(64) NOT NULL COMMENT '结算对象编号',
  posting_amount_cent BIGINT NOT NULL DEFAULT 0 COMMENT '入账金额，单位分，人民币',
  posting_status VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT '入账状态：INIT/REQUESTING/SUCCESS/FAILED/UNKNOWN',
  accounting_request_no VARCHAR(64) DEFAULT NULL COMMENT '账务请求号',
  fund_account_flow_no VARCHAR(64) DEFAULT NULL COMMENT '账户流水号',
  accounting_idempotent_key VARCHAR(128) NOT NULL COMMENT '账务平台幂等键',
  idempotent_key VARCHAR(128) NOT NULL COMMENT '清结算侧幂等键',
  request_hash VARCHAR(128) NOT NULL COMMENT '请求核心参数指纹',
  request_time DATETIME(3) DEFAULT NULL COMMENT '最近请求时间',
  success_time DATETIME(3) DEFAULT NULL COMMENT '成功时间',
  retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  fail_code VARCHAR(64) DEFAULT NULL COMMENT '失败码',
  fail_reason VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_posting_no (posting_no),
  UNIQUE KEY uk_ccs_posting_bill (bill_no),
  UNIQUE KEY uk_ccs_posting_biz (caller_system, biz_domain, biz_no, accounting_scene),
  UNIQUE KEY uk_ccs_posting_idem (idempotent_key),
  UNIQUE KEY uk_ccs_posting_acc_idem (accounting_idempotent_key),
  KEY idx_ccs_posting_status (posting_status, create_time),
  KEY idx_ccs_posting_accounting (accounting_request_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='账务入账单表';

CREATE TABLE IF NOT EXISTS ccs_settlement_operation_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  operation_no VARCHAR(64) NOT NULL COMMENT '操作日志编号',
  target_type VARCHAR(32) NOT NULL COMMENT '操作对象类型：POSITION/BATCH/BILL/POSTING',
  target_no VARCHAR(64) NOT NULL COMMENT '操作对象编号',
  operation_type VARCHAR(64) NOT NULL COMMENT '操作类型',
  before_status VARCHAR(32) DEFAULT NULL COMMENT '操作前状态',
  after_status VARCHAR(32) DEFAULT NULL COMMENT '操作后状态',
  operator_id VARCHAR(64) NOT NULL COMMENT '操作人ID',
  operator_name VARCHAR(128) DEFAULT NULL COMMENT '操作人名称',
  remark VARCHAR(512) DEFAULT NULL COMMENT '备注',
  request_hash VARCHAR(128) DEFAULT NULL COMMENT '请求核心参数指纹',
  ext_json JSON DEFAULT NULL COMMENT '扩展信息',
  version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ccs_operation_no (operation_no),
  KEY idx_ccs_operation_target (target_type, target_no, create_time),
  KEY idx_ccs_operation_operator (operator_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='结算操作日志表';
